---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pv-claim  # Sets name of PVC
  namespace: databases
  labels:
    app: mysql
spec:
  storageClassName: storage2-nvme-vcp-immediate
  accessModes:
    - ReadWriteOnce  # Sets read and write access
  resources:
    requests:
      storage: 10Gi  # Sets volume size
  volumeMode: Filesystem