apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage1-nvme-vcp-wffc
provisioner: kubernetes.io/vsphere-volume
parameters:
  datastore: iSCSI-Storage1-NVMe
reclaimPolicy: Delete
volumeBindingMode: Immediate