---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap-ca-crt
  namespace: awx
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
  - secretKey: ca-crt
    remoteRef:
      key: /v1/homelabsecrets/data/certs/ca
      property: ca-crt