---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap-ca-crt
  namespace: awx
spec:
  data:
  - secretKey: ca-crt
    remoteRef:
      key: /homelabsecrets/data/certs/ca
