---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bind-ldap-password
  namespace: awx
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
  - secretKey: ldap-password
    remoteRef: 
      key: /v1/homelabsecrets/data/ldap
      property: ldap-password
