# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: mysql-sa
#   namespace: databases
# #automountServiceAccountToken: false

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: mysql-databases-rolebinding
#   namespace: databases
# subjects:
# - kind: ServiceAccount
#   name: mysql-sa
#   namespace: databases
# roleRef:
#   kind: ClusterRole
#   name: system:openshift:scc:anyuid
#   apiGroup: rbac.authorization.k8s.io


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql  # Sets Deployment name
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      namespace: databases
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.3 # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3306  # Exposes container port
          env:
          - name: MYSQL_DATABASE
            value: mysqldatabase
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: mysql-k8s-root-password
                key: password
          resources:
            limits:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqldb
      volumes:
        - name: mysqldb
          persistentVolumeClaim:
            claimName: mysql-pv-claim