---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-k8s-root-password
  namespace: grafana
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
  - secretKey: ldap-ca.crt
    remoteRef:
      key: k8s/mysql/root
      property: password