apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres  # Sets Deployment name
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      namespace: grafana
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          securityContext:
            runAsUser: 1000
          image: postgres:latest # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          env:
          - name: POSTGRES_DB
            value: grafana
          - name: POSTGRES_USER
            value: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: postgres
                key: postgres_password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
              subPath: postgres
      serviceAccountName: "postgres-sa"
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim